version: "3.8"
services:
  redis_server:
    container_name: redis_server
    image: "redislabs/redismod"
    volumes:
      - redis_data:/data
    # ports: # enable to visualize data in redis insight
    #   - "6379:6379"
  mongodb_server:
    container_name: mongodb_server
    image: "mongo"
    volumes:
      - mongodb_data:/data/db
    ports: # enable to visualize data in mongodb compass
      - "${MONGODB_COMPASS_PORT}:27017"
  mongodb_seed:
    container_name: mongodb_seed
    build:
       context: ./
       dockerfile: dockerfile-mongodb-seed
       args:
         BUILD_BASE_PATH: database
    env_file:
      - ./.env
    depends_on:
      - mongodb_server
  cdn:
    container_name: cdn
    build:
       context: ./
       dockerfile: dockerfile-cdn
       args:
         BUILD_BASE_PATH: cdn
    ports:
      - "${CDN_PORT}:80"
  orders_service:
    container_name: orders_service
    build:
       context: ./
       dockerfile: dockerfile-server
       args:
         BUILD_BASE_PATH: server/src/services/orders
    env_file:
      - ./.env
    depends_on:
      - redis_server
      - mongodb_server
  order_history_service:
    container_name: order_history_service
    build:
       context: ./
       dockerfile: dockerfile-server
       args:
         BUILD_BASE_PATH: server/src/services/order-history
    env_file:
      - ./.env
    depends_on:
      - redis_server
      - mongodb_server
  products_service:
    container_name: products_service
    build:
       context: ./
       dockerfile: dockerfile-server
       args:
         BUILD_BASE_PATH: server/src/services/products
    env_file:
      - ./.env
    depends_on:
      - redis_server
      - mongodb_server    
  api_gateway:
    container_name: api_gateway
    build:
       context: ./
       dockerfile: dockerfile-server
       args:
         BUILD_BASE_PATH: server/src/api-gateway
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    env_file:
      - ./.env
    depends_on:
      - orders_service
      - order_history_service
  client:
    container_name: client
    build:
       context: ./
       dockerfile: dockerfile-client
       args:
         BUILD_BASE_PATH: client/nextjs
    ports:
      - "${FRONTEND_CLIENT_PORT}:${FRONTEND_CLIENT_PORT}"
    env_file:
      - ./.env
    stdin_open: true # -i input flag
    tty: true # -t terminal flag
    depends_on:
      - api_gateway
      - cdn

volumes:
  redis_data:
  mongodb_data: