version: "3.8"
services:
  redis_server: 
    image: "redislabs/redismod" 
    volumes:
      - redis_data:/data
    # ports: # enable to visualize data in redis insight 
    #   - "6379:6379"    
  mongodb_server: 
    image: "mongo" 
    volumes:
      - mongodb_data:/data/db 
    # ports: # enable to visualize data in mongodb compass 
    #   - "27017:27017"   
  orders_service:
    build:
       context: ./
       dockerfile: dockerfile-server 
       args:
         BUILD_BASE_PATH: server/src/services/orders
    env_file:
      - ./.env
    depends_on:
      - redis_server 
      - mongodb_server
  order_history_service:
    build:
       context: ./
       dockerfile: dockerfile-server 
       args:
         BUILD_BASE_PATH: server/src/services/order-history
    env_file:
      - ./.env
    depends_on:
      - redis_server 
      - mongodb_server
  api_gateway:
    build:
       context: ./
       dockerfile: dockerfile-server 
       args:
         BUILD_BASE_PATH: server/src/api-gateway
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}" 
    env_file:
      - ./.env
    depends_on:
      - orders_service 
      - order_history_service    

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend/src:/app/src
  #   stdin_open: true # -i input flag
  #   tty: true # -t terminal flag
  #   depends_on:
  #     - api_gateway

volumes:
  redis_data:
  mongodb_data: